name: 'Get terraform version'
description: 'Get terraform version from .terraform-version file'
inputs:
  path:
    description: 'where to run terraform command'
    required: false
    default: '.'
outputs:
  terraform-version:
    description: "detected terraform version"
    value: ${{ steps.get-terraform-version.outputs.terraform-version }}
runs:
  using: composite
  steps:
    - id: get-terraform-version
      run: |
        result=$(${{ github.action_path }}/script.sh ${{ inputs.path }})
        echo "::set-output name=terraform-version::$(echo $result)"
      shell: bash
