name: test action

'on': [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo '0.11.*' > .terraform-version
    - id: get-terraform-version-action
      uses: bigwheel/get-terraform-version-action@v0.1.0
    - run: test '0.11.15' = "${{ steps.get-terraform-version-action.outputs.terraform-version }}"
