name: test action

'on': [push]

jobs:
  success_case:
    runs-on: ubuntu-latest
    steps:
    - run: echo '0.11.*' > .terraform-version
    - id: get-terraform-version-action
      uses: bigwheel/get-terraform-version-action@main
    - run: test "${{ steps.get-terraform-version-action.outputs.terraform-version }}" = '0.11.15'
  failue_case:
    runs-on: ubuntu-latest
    steps:
    - id: get-terraform-version-action
      uses: bigwheel/get-terraform-version-action@main
      continue-on-error: true
    - run: test "${{ steps.get-terraform-version-action.outcome}}" = 'failure'
