name: test action

'on': [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: bigwheel/get-terraform-version-action@v1
      with:
        who-to-greet: 'Mona the Octocat'
    - run: echo random-number ${{ steps.foo.outputs.random-number }}
